backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: jargon
    label: Jargon
    folder: jargon
    create: true
    fields:
      - { name: name, label: name }
      - { name: when-to-use, label: When To Use }
      - { name: sentence, label: Sentence }
      - { name: explanation, label: Explanation, widget: markdown }
      - { name: resources, label: Resources, widget: list }
